In [7]:
# Funções internas
print(abs(-200))  # Retorna o valor absoluto
lst = [1,2,3,4,5,6,987]
print(max(lst))
print(min(lst))
print(sum(lst))
print(round(2.345677))

200
987
1
1008
2


In [14]:
# Estatística
from statistics import mean, median, mode
print('Média: ', mean(lst))
print('Mediana: ', median(lst))
print('Moda: ', mode(lst))


Média:  144
Mediana:  4
Moda:  1


In [15]:
# Desvio padrão da amostra
from statistics import stdev
print('Desvio padrão: ', stdev(lst))

Desvio padrão:  371.73198230266206


In [17]:
# Variância da amostra
from statistics import variance
print('Variância: ', variance(lst))

Variância:  138184.66666666666


In [19]:
from numpy import random
a = random.random((3,3))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[0.9165861  0.971031   0.15975681]
 [0.77215849 0.38775276 0.99928255]
 [0.35584736 0.13032933 0.02497122]]
