In [2]:
import numpy as np

In [3]:
# Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [5]:
# Cria o array com um tipo específico
# Cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))


[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# Mudar o tipo do array
# Podemos transformar tipos de dados de arrays

mtnew = np.array([1.5, 3.6, -5.1, 9.42, 4.99999])
print(mtnew)

# Quando transformamos de float para int os valores truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.5      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]


In [8]:
# Podemos converter um array do tipo inteiro para Float

mt5 = np.array([1,2,3,4,5])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [9]:
# Mais de uma dimensão
# Cria uma matriz bidimensional
mt7 = np.array([[7,2,3], [12,27,4], [5,34,23]])
print(mt7)


[[ 7  2  3]
 [12 27  4]
 [ 5 34 23]]


In [11]:
# Criar arrays vazios tipificados
# Empty significa que não são inicializados, não que são vazios
vazios = np.empty([3,2], dtype = int)
print(vazios)
print('                   .                     ')

# Cria uma matriz 4x3 (l x C) com valores zero
zeros = np.zeros([4,3])
print(zeros)
print('                   .                     ')

# Com valores igual a um
um = np.ones([5,7])
print(um)
print('                   .                     ')

# Cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
                   .                     
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
                   .                     
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
                   .                     
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# Valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print('                   .                     ')

# Valores aleatórios destr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print('                   .                     ')

# Valores aleatórios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)


[0.26010329 0.42357138 0.34388272 0.18984311 0.30195189]
                   .                     
[ 1.28266416  0.76130124 -1.19868858  0.71000637  0.98247125]
                   .                     
[[7.60566678 5.73167816 9.75902389 5.00458474]
 [5.93434717 7.69866421 1.10075409 1.53303257]
 [0.24272125 7.58059826 1.93707877 4.57779981]]


In [19]:
# Outra forma de gerar aleatórios
# Uso de semente
gnr = np.random.default_rng(10)
ale5 = gnr.random(3)
print(ale5)

# Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.95600171 0.20768181 0.82844489]
[[5 1 8 5]
 [1 1 4 6]
 [4 8 0 4]]


In [20]:
# Unique remove repetições
j = np.array([1,2,3,3,2,3,1,3,4,5,6,7,7,77,6,5,333,1,1,3])
j = np.unique(j)
print(j)

[  1   2   3   4   5   6   7  77 333]


In [26]:
# Funções específicas
# Cria matriz bidimensional k
k = np.array([[1,2,3], [2,3,5], [45,6,7]])
print(k)

# Mostra um elemento específico da matriz k
print(k[0][2])

# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[ 1  2  3]
 [ 2  3  5]
 [45  6  7]]
3
(3, 3)


In [32]:
# Funções matemáticas
# Mostra o maior valor da matriz k
print(k.max())

# Mostra o menor valor da matriz k
print(k.min())

# Mostra a soma dos valores da matriz k
print(k.sum())

# Mostra o valor da média dos valores da matriz k
print(k.mean())
 
# mostra o valor dos desvio padrão (standard deviation) dos valores da matriz k
print(k.std())

45
1
74
8.222222222222221
13.13838970158129


In [36]:
# Funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos os elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

# Mostra o valor exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [37]:
# Extração de elementos
m = np.array([1,2,3,4,5,6])

# Mostra o elemento da posição 2
print(m[1])

# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])

# Mostra o array criado a partir da 2a posição até todo o restante do array
print(m[1:])

# Mostra o array criado a partir da antepenúltima posição até o fim
print(m[-3:])

2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [39]:
# Extração de linha e colunas
l = np.array([[4,5], [6,1], [7,4]])
print(l)

# Primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)

# Segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)

# Terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)

# Todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)

# Todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
[4 5]
[6 1]
[7 4]
[4 6 7]
[5 1 4]


In [11]:
# Adição e multiplicação de matrizes
n = np.array([[1,2], [3,4]])
o = np.array([[1,1], [1,1]])
res1 = n + o
print(res1)

res2 = n * o
print(res2)

p = np.array([[1,2], [3,4], [5,6]])
q = np.array([2,1])
print(p + q)
print(p * q)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[3 3]
 [5 5]
 [7 7]]
[[ 2  2]
 [ 6  4]
 [10  6]]


In [13]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# e 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))

# Mostra as matrizes transpostas entre linha e coluna
print(f)

s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [14]:
# Outra forma de fazer a transposição
r = np.arange(15).reshape((3,5))
print(r)

# Rearranja um conjunto de 15 elementos
# Mostra as matrizes transpostas entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [16]:
# Expressões lógicas
# Usando where
# Criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)

# Criando matriz com valores booleanos baseados no array v
x = (v > 0)
print(x)

# Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)


[[ 0.05774138  0.38763075  2.25327842 -0.74881149]
 [ 0.65735267  0.9951499  -0.22661952 -0.23477851]
 [-0.77636901 -1.83219125 -0.13588669 -1.03591235]
 [ 0.09247224 -0.71292825 -1.39228655 -0.56911592]]
[[ True  True  True False]
 [ True  True False False]
 [False False False False]
 [ True False False False]]
[[ 1  1  1 -1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]
 [ 1 -1 -1 -1]]
